/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.yourcompany.struts.action;

import java.sql.Connection;
import java.sql.Date;
import java.sql.Timestamp;
import java.text.SimpleDateFormat;
import java.util.Arrays;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.yourcompany.struts.bean.Person;
import com.yourcompany.struts.dao.PersonDAO;
import com.yourcompany.struts.form.PersonForm;

/** 
 * MyEclipse Struts
 * Creation date: 10-17-2017
 * 
 * XDoclet definition:
 * @struts.action path="/person" name="personForm" input="/form/addPerson.jsp" scope="request" validate="true"
 * @struts.action-forward name="success" path="/form/addPersonSuccess.jsp"
 * @struts.action-forward name="list" path="/form/listPerson.jsp"
 */
public class PersonAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form, HttpServletRequest request,
			HttpServletResponse response) throws Exception{
		PersonForm personForm = (PersonForm) form;// TODO Auto-generated method stub
		if("add".equals(personForm.getAction())){
			return add(mapping,form,request,response);
		}else if("list".equals(personForm.getAction())){
			return list(mapping,form,request,response);
		}
		return mapping.getInputForward();
	}
	
	public ActionForward add(ActionMapping mapping, ActionForm form, HttpServletRequest request,HttpServletResponse response)
						throws Exception{
		PersonForm personForm = (PersonForm) form;
		Date birthday = new Date(new SimpleDateFormat("yy-MM-dd").parse(personForm.getBirthday()).getTime());
		
		Person person=new Person();
		person.setAccount(personForm.getAccount());
		person.setName(personForm.getName());
		person.setSecret(personForm.isSecret());
		person.setCreateDate(new Timestamp(System.currentTimeMillis()));
		
		person.setBirthday(birthday);
		person.setHobby(Arrays.asList(personForm.getHobby()));
		
		PersonDAO personDAO = new PersonDAO();
		Connection conn = getDataSource(request).getConnection();
		
		personDAO.addPerson(conn, person);
		request.setAttribute("person", person);
		return mapping.findForward("success");
		
	}
	
	public ActionForward list(ActionMapping mapping, ActionForm form, HttpServletRequest request, HttpServletResponse response)
						throws Exception{
		
		PersonDAO personDAO = new PersonDAO();
		Connection conn = getDataSource(request).getConnection();
		
		List<Person> personList = personDAO.listPersons(conn);
		request.setAttribute("personList", personList);
		return mapping.findForward("list");
		
		
	}
}